[package]
name = "server"
version = "0.1.0"
authors = ["Constantine Solovev <constantine.solovev@gmail.com>"]
edition = "2018"

[dependencies]


tokio = "0.1"
futures = "0.1"
async-kvstore = { git="https://github.com/RicoGit/async-kvstore.git", branch="master" }
